# Android
# assembleRelease your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save assembleRelease artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: firebase
  - group: tv-google-play

parameters:
  - name: release_notes
    displayName: Release notes
    type: string

  - name: tester_groups
    displayName: Tester groups
    type: string
    default: middleware
    values:
      - middleware
      - testers
      - 'middleware, testers'

resources:
  pipelines:
  - pipeline: Middleware   # Name of the pipeline resource
    source: Middleware # Name of the pipeline referenced by the pipeline resource
    # project: FabrikamProject # Required only if the source pipeline is in another project
    trigger: true # Run app-ci pipeline when any run of security-lib-ci completes

steps:
  - bash:
      echo "y" | sudo $(ANDROID_SDK_ROOT)/tools/bin/sdkmanager --install "ndk;21.0.6113669" --sdk_root=${ANDROID_SDK_ROOT}
    displayName: 'Setup NDK 21.0.6113669'

  - task: CmdLine@2
    inputs:
      script: curl -sL firebase.tools | bash
    displayName: 'Install firebase tools'

  - task: MavenAuthenticate@0
    displayName: 'Maven Authenticate'
    inputs:
      artifactsFeeds: 'middleware, nextgen'

  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      javaHomeOption: 'JDKVersion'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      options: '-PversionCode=$(Build.BuildId) -PstoreFile=$(storeFile) -Ppassword=$(password) -PkeyAlias=$(keyAlias) -PkeyPassword=$(keyPassword)'
      tasks: 'clean assembleDebug'
    displayName: gradlew assembleDebug

  - task: CopyFiles@2
    displayName: 'Copy .apk files to artifact staging directory'
    inputs:
      SourceFolder: '$(system.defaultworkingdirectory)'
      Contents: '**/*.apk'
      flattenFolders: true
      TargetFolder: '$(build.artifactstagingdirectory)'
    condition: succeededOrFailed()

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
    condition: succeededOrFailed()
    displayName: 'Publish Artifact: drop'

  - task: CmdLine@2
    inputs:
      script: firebase appdistribution:distribute $(Build.ArtifactStagingDirectory)/*.apk --app $(tv-app-token) --token "$(firebase-token)" --release-notes "${{ parameters.release_notes }}" --groups "${{ parameters.tester_groups }}"
    displayName: 'Distribute app to Firebase'